@startuml IntegrationJira
title Jira Integration Flow
participant Timelapse
participant JiraAdapter
participant JiraAPI

Timelapse -> JiraAdapter: Request Sync (LastCheckpoint)
JiraAdapter -> JiraAPI: GET /rest/api/2/search?jql=updated > Checkpoint
JiraAPI -> JiraAdapter: Return JSON (Issues)
JiraAdapter -> JiraAdapter: Map JiraIssue -> TimelapseTask
JiraAdapter -> Timelapse: Return Normalized Data
@enduml
