@startuml ClassTasks
package "Core Models" {
    class Task {
        +String _id
        +String externalId
        +String title
        +String description
        +Status status
        +Priority priority
        +DateTime createdAt
        +sync()
        +startTimer()
    }
    
    class TimeEntry {
        +String _id
        +DateTime startDate
        +DateTime endDate
        +Int durationSeconds
        +String taskId
        +Boolean isSynced
        +calculateDuration()
    }
    
    Task "1" *-- "0..*" TimeEntry : possui
}
@enduml
